import {
  Injectable,
  UnauthorizedException,
  BadRequestException,
  ConflictException,
} from "@nestjs/common";
import { JwtService } from "@nestjs/jwt";
import { ConfigService } from "@nestjs/config";
import { authenticator } from "otplib";
import * as qrcode from "qrcode";
import * as bcrypt from "bcrypt";
import { customAlphabet } from "nanoid";
import { PrismaService } from "../prisma/prisma.service";
import type { AuthResponse, JwtPayload, MfaSetupResponse } from "@hms/types";
import { PERMISSIONS } from "@hms/config";
import { LoginDto } from "./dto/login.dto";

const genBackup = customAlphabet("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", 10);

const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  HOSPITAL_ADMIN: Object.values(PERMISSIONS),
  DOCTOR: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_UPDATE,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_CREATE,
    PERMISSIONS.RADIOLOGY_READ, PERMISSIONS.RADIOLOGY_ORDER,
    PERMISSIONS.PHARMACY_READ, PERMISSIONS.PHARMACY_CREATE,
    PERMISSIONS.BILLING_READ, PERMISSIONS.ROSTER_READ,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.REFERRALS_READ, PERMISSIONS.REFERRALS_CREATE, PERMISSIONS.REFERRALS_MANAGE,
    PERMISSIONS.OPD_READ, PERMISSIONS.OPD_MANAGE,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.BLOOD_BANK_READ, PERMISSIONS.BLOOD_BANK_MANAGE,
    PERMISSIONS.INSURANCE_READ, PERMISSIONS.INSURANCE_MANAGE,
    PERMISSIONS.MORTUARY_READ,
    PERMISSIONS.THEATRE_READ, PERMISSIONS.THEATRE_MANAGE,
    PERMISSIONS.CARE_PLAN_READ, PERMISSIONS.CARE_PLAN_MANAGE,
    PERMISSIONS.DIETARY_READ, PERMISSIONS.DIETARY_MANAGE,
    PERMISSIONS.TRIAGE_READ, PERMISSIONS.TRIAGE_MANAGE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.CERTIFICATES_READ, PERMISSIONS.CERTIFICATES_MANAGE,
    PERMISSIONS.VISITORS_READ,
    PERMISSIONS.APPRAISALS_READ,
    PERMISSIONS.FEEDBACK_READ,
    PERMISSIONS.TRANSPORT_READ,
    PERMISSIONS.MAR_READ, PERMISSIONS.MAR_MANAGE,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.ALERTS_READ, PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.HANDOVER_READ, PERMISSIONS.HANDOVER_MANAGE,
    PERMISSIONS.REHAB_READ,
    PERMISSIONS.ENCOUNTERS_READ, PERMISSIONS.ENCOUNTERS_MANAGE,
    PERMISSIONS.ADMISSIONS_READ, PERMISSIONS.ADMISSIONS_MANAGE,
    PERMISSIONS.CHARGES_READ,
    PERMISSIONS.CATALOGUE_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  NURSE: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_UPDATE,
    PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.LAB_READ, PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.RADIOLOGY_READ,
    PERMISSIONS.REFERRALS_READ,
    PERMISSIONS.OPD_READ, PERMISSIONS.OPD_MANAGE,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.BLOOD_BANK_READ,
    PERMISSIONS.MORTUARY_READ,
    PERMISSIONS.THEATRE_READ,
    PERMISSIONS.CARE_PLAN_READ, PERMISSIONS.CARE_PLAN_MANAGE,
    PERMISSIONS.DIETARY_READ, PERMISSIONS.DIETARY_MANAGE,
    PERMISSIONS.TRIAGE_READ, PERMISSIONS.TRIAGE_MANAGE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.VISITORS_READ, PERMISSIONS.VISITORS_MANAGE,
    PERMISSIONS.FEEDBACK_READ,
    PERMISSIONS.TRANSPORT_READ,
    PERMISSIONS.MAR_READ, PERMISSIONS.MAR_MANAGE,
    PERMISSIONS.MAINTENANCE_READ, PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.ALERTS_READ, PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.HANDOVER_READ, PERMISSIONS.HANDOVER_MANAGE,
    PERMISSIONS.REHAB_READ, PERMISSIONS.REHAB_MANAGE,
    PERMISSIONS.WARD_ROUND_READ, PERMISSIONS.WARD_ROUND_MANAGE,
    PERMISSIONS.CONSENT_READ, PERMISSIONS.CONSENT_MANAGE,
    PERMISSIONS.DISCHARGE_READ, PERMISSIONS.DISCHARGE_MANAGE,
    PERMISSIONS.ROSTER_READ, PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ENCOUNTERS_READ, PERMISSIONS.ENCOUNTERS_MANAGE,
    PERMISSIONS.ADMISSIONS_READ, PERMISSIONS.ADMISSIONS_MANAGE,
    PERMISSIONS.CATALOGUE_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  RECEPTIONIST: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.PATIENTS_CREATE,
    PERMISSIONS.APPOINTMENTS_READ, PERMISSIONS.APPOINTMENTS_CREATE, PERMISSIONS.APPOINTMENTS_CANCEL,
    PERMISSIONS.BILLING_READ, PERMISSIONS.ROSTER_READ,
    PERMISSIONS.RADIOLOGY_READ,
    PERMISSIONS.OPD_READ, PERMISSIONS.OPD_MANAGE,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.INSURANCE_READ,
    PERMISSIONS.MORTUARY_READ, PERMISSIONS.MORTUARY_MANAGE,
    PERMISSIONS.THEATRE_READ,
    PERMISSIONS.TRIAGE_READ, PERMISSIONS.TRIAGE_MANAGE,
    PERMISSIONS.VISITORS_READ, PERMISSIONS.VISITORS_MANAGE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.FEEDBACK_READ, PERMISSIONS.FEEDBACK_MANAGE,
    PERMISSIONS.TRANSPORT_READ, PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.MAINTENANCE_READ, PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.HANDOVER_READ,
    PERMISSIONS.WARD_ROUND_READ,
    PERMISSIONS.CONSENT_READ, PERMISSIONS.CONSENT_MANAGE,
    PERMISSIONS.DISCHARGE_READ,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ENCOUNTERS_READ, PERMISSIONS.ENCOUNTERS_MANAGE,
    PERMISSIONS.ADMISSIONS_READ,
    PERMISSIONS.CATALOGUE_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
  CASHIER: [
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.INSURANCE_READ, PERMISSIONS.INSURANCE_MANAGE,
    PERMISSIONS.PROCUREMENT_READ,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.ENCOUNTERS_READ,
    PERMISSIONS.ADMISSIONS_READ,
    PERMISSIONS.CHARGES_READ, PERMISSIONS.CHARGES_MANAGE,
    PERMISSIONS.CATALOGUE_READ, PERMISSIONS.CATALOGUE_MANAGE,
    PERMISSIONS.SETTINGS_READ,
  ],
  LAB_TECHNOLOGIST: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_UPDATE,
    PERMISSIONS.BLOOD_BANK_READ, PERMISSIONS.BLOOD_BANK_MANAGE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  RADIOLOGIST: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.RADIOLOGY_READ, PERMISSIONS.RADIOLOGY_ORDER, PERMISSIONS.RADIOLOGY_RESULT,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  PHARMACIST: [
    PERMISSIONS.PATIENTS_READ,
    PERMISSIONS.PHARMACY_READ, PERMISSIONS.PHARMACY_CREATE, PERMISSIONS.PHARMACY_UPDATE,
    PERMISSIONS.BILLING_READ, PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.ATTENDANCE_READ,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE,
    PERMISSIONS.PROCUREMENT_READ, PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  HR_OFFICER: [
    PERMISSIONS.STAFF_READ, PERMISSIONS.STAFF_CREATE, PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.ROSTER_READ, PERMISSIONS.ROSTER_MANAGE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.PROCUREMENT_READ,
    PERMISSIONS.ASSETS_READ, PERMISSIONS.ASSETS_MANAGE,
    PERMISSIONS.PAYROLL_READ, PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.CERTIFICATES_READ,
    PERMISSIONS.VISITORS_READ,
    PERMISSIONS.APPRAISALS_READ, PERMISSIONS.APPRAISALS_MANAGE,
    PERMISSIONS.FEEDBACK_READ,
    PERMISSIONS.TRANSPORT_READ,
    PERMISSIONS.MAINTENANCE_READ, PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_MANAGE,
    PERMISSIONS.SETTINGS_READ,
  ],
  AUDITOR: [
    PERMISSIONS.ADMIN_AUDIT, PERMISSIONS.BILLING_READ,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.INCIDENTS_READ,
    PERMISSIONS.INSURANCE_READ,
    PERMISSIONS.PROCUREMENT_READ,
    PERMISSIONS.ASSETS_READ,
    PERMISSIONS.PAYROLL_READ,
    PERMISSIONS.APPRAISALS_READ,
    PERMISSIONS.FEEDBACK_READ,
    PERMISSIONS.MAR_READ,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.ALERTS_READ,
    PERMISSIONS.HANDOVER_READ,
    PERMISSIONS.REHAB_READ,
    PERMISSIONS.WARD_ROUND_READ,
    PERMISSIONS.CONSENT_READ,
    PERMISSIONS.DISCHARGE_READ,
    PERMISSIONS.SETTINGS_READ,
  ],
  DEPARTMENT_HEAD: [
    PERMISSIONS.PATIENTS_READ, PERMISSIONS.APPOINTMENTS_READ,
    PERMISSIONS.STAFF_READ, PERMISSIONS.LAB_READ, PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.RADIOLOGY_READ, PERMISSIONS.RADIOLOGY_ORDER,
    PERMISSIONS.BILLING_READ, PERMISSIONS.ROSTER_READ, PERMISSIONS.ROSTER_MANAGE,
    PERMISSIONS.LEAVE_READ, PERMISSIONS.LEAVE_APPLY, PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.OPD_READ, PERMISSIONS.OPD_MANAGE,
    PERMISSIONS.ATTENDANCE_READ, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.INCIDENTS_READ, PERMISSIONS.INCIDENTS_CREATE, PERMISSIONS.INCIDENTS_MANAGE,
    PERMISSIONS.BLOOD_BANK_READ, PERMISSIONS.BLOOD_BANK_MANAGE,
    PERMISSIONS.INSURANCE_READ, PERMISSIONS.INSURANCE_MANAGE,
    PERMISSIONS.MORTUARY_READ, PERMISSIONS.MORTUARY_MANAGE,
    PERMISSIONS.THEATRE_READ, PERMISSIONS.THEATRE_MANAGE,
    PERMISSIONS.CARE_PLAN_READ, PERMISSIONS.CARE_PLAN_MANAGE,
    PERMISSIONS.DIETARY_READ, PERMISSIONS.DIETARY_MANAGE,
    PERMISSIONS.TRIAGE_READ, PERMISSIONS.TRIAGE_MANAGE,
    PERMISSIONS.ASSETS_READ, PERMISSIONS.ASSETS_MANAGE,
    PERMISSIONS.PROCUREMENT_READ, PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.PAYROLL_READ, PERMISSIONS.PAYROLL_MANAGE,
    PERMISSIONS.CERTIFICATES_READ, PERMISSIONS.CERTIFICATES_MANAGE,
    PERMISSIONS.VISITORS_READ, PERMISSIONS.VISITORS_MANAGE,
    PERMISSIONS.APPRAISALS_READ, PERMISSIONS.APPRAISALS_MANAGE,
    PERMISSIONS.FEEDBACK_READ, PERMISSIONS.FEEDBACK_MANAGE,
    PERMISSIONS.TRANSPORT_READ, PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.MAR_READ, PERMISSIONS.MAR_MANAGE,
    PERMISSIONS.MAINTENANCE_READ, PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.TRAINING_READ, PERMISSIONS.TRAINING_MANAGE,
    PERMISSIONS.ALERTS_READ, PERMISSIONS.ALERTS_MANAGE,
    PERMISSIONS.HANDOVER_READ, PERMISSIONS.HANDOVER_MANAGE,
    PERMISSIONS.REHAB_READ, PERMISSIONS.REHAB_MANAGE,
    PERMISSIONS.WARD_ROUND_READ, PERMISSIONS.WARD_ROUND_MANAGE,
    PERMISSIONS.CONSENT_READ, PERMISSIONS.CONSENT_MANAGE,
    PERMISSIONS.DISCHARGE_READ, PERMISSIONS.DISCHARGE_MANAGE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.DASHBOARD_VIEW,
  ],
};

@Injectable()
export class AuthService {
  constructor(
    private prisma: PrismaService,
    private jwt: JwtService,
    private config: ConfigService,
  ) {}

  async login(dto: LoginDto, ip?: string, userAgent?: string): Promise<AuthResponse> {
    const user = await this.prisma.user.findUnique({
      where: { email: dto.email },
      include: { staff: true },
    });

    if (!user || !(await bcrypt.compare(dto.password, user.passwordHash))) {
      throw new UnauthorizedException("Invalid email or password");
    }

    if (user.status !== "ACTIVE") {
      throw new UnauthorizedException("Account is not active");
    }

    if (user.mfaEnabled) {
      if (!dto.totpCode) {
        throw new UnauthorizedException("MFA_REQUIRED");
      }
      const valid = authenticator.verify({ token: dto.totpCode, secret: user.mfaSecret! });
      if (!valid) throw new UnauthorizedException("Invalid 2FA code");
    }

    const permissions = ROLE_PERMISSIONS[user.role] ?? [];
    const payload: JwtPayload = {
      sub: user.id,
      email: user.email,
      role: user.role as any,
      permissions,
      staffId: user.staff?.id ?? null,
      organizationId: user.organizationId,
    };

    const accessToken = this.jwt.sign(payload);
    const refreshToken = await this.generateRefreshToken(user.id, ip, userAgent);

    await this.prisma.user.update({
      where: { id: user.id },
      data: { lastLoginAt: new Date(), lastLoginIp: ip },
    });

    return {
      accessToken,
      refreshToken,
      user: {
        id: user.id,
        email: user.email,
        name: `${user.staff?.firstName ?? ""} ${user.staff?.lastName ?? ""}`.trim(),
        role: user.role as any,
        permissions,
        staffId: user.staff?.id ?? null,
      },
    };
  }

  async refreshTokens(token: string): Promise<{ accessToken: string; refreshToken: string }> {
    const stored = await this.prisma.refreshToken.findUnique({
      where: { token },
      include: { user: { include: { staff: true } } },
    });

    if (!stored || stored.isRevoked || stored.expiresAt < new Date()) {
      throw new UnauthorizedException("Invalid or expired refresh token");
    }

    await this.prisma.refreshToken.update({ where: { id: stored.id }, data: { isRevoked: true } });

    const permissions = ROLE_PERMISSIONS[stored.user.role] ?? [];
    const payload: JwtPayload = {
      sub: stored.user.id,
      email: stored.user.email,
      role: stored.user.role as any,
      permissions,
      staffId: stored.user.staff?.id ?? null,
      organizationId: stored.user.organizationId,
    };

    const accessToken = this.jwt.sign(payload);
    const refreshToken = await this.generateRefreshToken(stored.user.id);
    return { accessToken, refreshToken };
  }

  async logout(token: string) {
    await this.prisma.refreshToken.updateMany({
      where: { token },
      data: { isRevoked: true },
    });
  }

  async setupMfa(userId: string): Promise<MfaSetupResponse> {
    const user = await this.prisma.user.findUniqueOrThrow({ where: { id: userId } });
    if (user.mfaEnabled) throw new ConflictException("MFA is already enabled");

    const secret = authenticator.generateSecret();
    const otpauth = authenticator.keyuri(user.email, "CareSync HMS", secret);
    const qrCodeDataUrl = await qrcode.toDataURL(otpauth);
    const backupCodes = Array.from({ length: 10 }, () => genBackup());

    await this.prisma.user.update({
      where: { id: userId },
      data: { mfaSecret: secret, mfaBackupCodes: backupCodes },
    });

    return { secret, qrCodeDataUrl, backupCodes };
  }

  async enableMfa(userId: string, code: string) {
    const user = await this.prisma.user.findUniqueOrThrow({ where: { id: userId } });
    if (!user.mfaSecret) throw new BadRequestException("MFA setup not initiated");
    const valid = authenticator.verify({ token: code, secret: user.mfaSecret });
    if (!valid) throw new BadRequestException("Invalid verification code");
    await this.prisma.user.update({ where: { id: userId }, data: { mfaEnabled: true } });
  }

  private async generateRefreshToken(userId: string, ip?: string, userAgent?: string): Promise<string> {
    const { customAlphabet: ca } = await import("nanoid");
    const gen = ca("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", 64);
    const token = gen();
    const expiresAt = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
    await this.prisma.refreshToken.create({
      data: { token, userId, expiresAt, ipAddress: ip, userAgent },
    });
    return token;
  }
}
