import { Injectable, Logger, InternalServerErrorException } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { createHash, randomUUID } from "crypto";
import { createReadStream, existsSync } from "fs";
import { mkdir, writeFile, unlink, stat } from "fs/promises";
import { join, extname, resolve, sep } from "path";

export interface StoredFile {
  storageKey: string;
  checksum: string;
  sizeBytes: number;
}

/**
 * Where uploaded bytes live.
 *
 * Deliberately local disk. `AWS_S3_*` has sat in the environment template
 * since the first commit with nothing reading it, and shipping an untested S3
 * path would be worse than shipping none — so the interface here is the seam
 * an S3 driver would slot into, and the config is marked as unimplemented
 * rather than left looking functional.
 *
 * Two rules the rest of the system depends on:
 *  - the key is generated here and never derived from the uploader's filename,
 *    so "../../etc/passwd" is not a path this can be talked into writing to;
 *  - the root sits outside anything the web server serves, so a file is only
 *    ever reachable through an endpoint that checks who is asking.
 */
@Injectable()
export class StorageService {
  private readonly logger = new Logger(StorageService.name);
  private readonly root: string;

  constructor(private config: ConfigService) {
    this.root = resolve(
      this.config.get<string>("FILE_STORAGE_ROOT") ?? join(process.cwd(), "storage", "documents"),
    );
  }

  /** Directory layout is by year and month, so one folder never grows unbounded. */
  private keyFor(originalName: string): string {
    const now = new Date();
    const yyyy = now.getFullYear();
    const mm = String(now.getMonth() + 1).padStart(2, "0");

    // Only the extension survives from the client's name, and even that is
    // restricted to plain alphanumerics.
    const raw = extname(originalName).slice(0, 12).toLowerCase();
    const ext = /^\.[a-z0-9]+$/.test(raw) ? raw : "";

    return `${yyyy}/${mm}/${randomUUID()}${ext}`;
  }

  /**
   * Resolves a key to an absolute path, refusing anything that escapes the
   * root. Keys are generated by this service, but a key also arrives from the
   * database on download, and a corrupted or tampered row must not be able to
   * read arbitrary files off the disk.
   */
  private pathFor(storageKey: string): string {
    const full = resolve(this.root, storageKey);
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new InternalServerErrorException("Refusing to read outside the document store");
    }
    return full;
  }

  async save(buffer: Buffer, originalName: string): Promise<StoredFile> {
    const storageKey = this.keyFor(originalName);
    const full = this.pathFor(storageKey);

    await mkdir(join(full, ".."), { recursive: true });
    await writeFile(full, buffer);

    return {
      storageKey,
      checksum: createHash("sha256").update(buffer).digest("hex"),
      sizeBytes: buffer.length,
    };
  }

  exists(storageKey: string): boolean {
    return existsSync(this.pathFor(storageKey));
  }

  stream(storageKey: string) {
    return createReadStream(this.pathFor(storageKey));
  }

  async sizeOf(storageKey: string): Promise<number> {
    return (await stat(this.pathFor(storageKey))).size;
  }

  /**
   * Removes the bytes. Used only when a database write failed after the file
   * landed — deleting a document is a soft delete, because a record that was
   * part of someone's care has to stay producible.
   */
  async discard(storageKey: string): Promise<void> {
    try {
      await unlink(this.pathFor(storageKey));
    } catch (err) {
      this.logger.warn(`Could not discard orphaned upload ${storageKey}: ${String(err)}`);
    }
  }
}
